window.TREE_BRIDGE_CONFIG = {
  projectName: "TREE Bridge",
  sourceChain: "Sui",
  destinationChain: "BNB Chain",
  logoAsset: "assets/treetoken-logo.webp",
  heroAsset: "assets/tree-hero-city.jpg",
  sourceTokenLabel: "TREE on Sui",
  sourceTokenType: "0x6c5a609f6d0288523ce4a6ed87d19ae127f62073ab75fd9b0b1c9b455d4895cf::tree::TREE",
  officialAxelarRoute:
    "https://interchain.axelar.dev/sui/0x6c5a609f6d0288523ce4a6ed87d19ae127f62073ab75fd9b0b1c9b455d4895cf::tree::TREE",
  executionMode: "direct-sui-wallet",
  directBridge: {
    enabled: false,
    status: "needs_verified_axelar_sui_constants",
    sourceChainId: "sui:mainnet",
    destinationChain: "BNB Chain",
    destinationChainAxelarKey: "",
    tokenId: "",
    itsPackageId: "",
    itsObjectId: "",
    gatewayPackageId: "",
    gatewayObjectId: "",
    gasServicePackageId: "",
    gasServiceObjectId: "",
    signerFeature: "sui:signAndExecuteTransaction",
    requiredBeforeEnable: [
      "Axelar ITS tokenId for TREE",
      "Axelar Sui ITS package and shared object IDs",
      "Axelar Sui gateway package and shared object IDs",
      "Axelar Sui gas service package and shared object IDs",
      "Axelar destination-chain key for BNB Chain",
      "TREE decimals and smallest-unit amount handling",
    ],
  },
  destinationTokenAddress: "",
  destinationLiquidityVenue: "",
  launchNotes: [
    "Use the in-page Sui wallet flow as the primary execution surface.",
    "Keep the Axelar route as a temporary fallback until direct signing is fully verified.",
    "Test with a small amount before project funding, liquidity moves, or public campaigns.",
    "Add the BNB-side token address and liquidity venue after they are confirmed.",
  ],
};
